apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-cloud-deployment
  labels:
    app: edge-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edge-cloud
  template:
    metadata:
      labels:
        app: edge-cloud
    spec:
      containers:
      - name: service-auth
        image: gcr.io/securescalergcp/service_auth:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "50m"     # Lowered CPU request
            memory: "256Mi" # Lowered memory request
          limits:
            cpu: "100m"    # Lowered CPU limit
            memory: "512Mi" # Lowered memory limit
      - name: service-data
        image: gcr.io/securescalergcp/service_data:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
      - name: service-notification
        image: gcr.io/securescalergcp/service_notification:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
      - name: service-pubsub
        image: gcr.io/securescalergcp/service_pubsub:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-cloud-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-cloud-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20